name: meal_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  bloc: ^8.1.1
  buildcondition: ^0.0.4
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.5
  dart_code_metrics: ^5.5.1
  device_preview: ^1.1.0
  dio: ^5.0.3
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_compass: ^0.7.0
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_mobile_ads: ^2.4.0
  google_sign_in: ^6.0.2
  in_app_review: ^2.0.6
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  material_floating_search_bar: ^0.3.7
  permission_handler: ^10.2.0
  queen_validators: ^1.0.1
  responsive_sizer: ^3.1.1
  share_plus: ^6.3.1
  shared_preferences: ^2.0.20
  smooth_page_indicator: ^1.0.1
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.10
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: "^0.12.0"
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1

flutter_native_splash:
  image: assets/images/islamGreen.png
  color: "#ffffff"

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/islamGreen.png
  # adaptive_icon_background: assets/images/background.png
  # adaptive_icon_foreground: assets/images/foreground.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Anuphan
      fonts:
        - asset: assets/fonts/Anuphan-Bold.ttf
        - asset: assets/fonts/Anuphan-Regular.ttf
