// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFyya2ClMTCOoIJj8Dc99PoPNnKAQHnUc',
    appId: '1:75820450814:android:ca2eae95264ccd800d36af',
    messagingSenderId: '75820450814',
    projectId: 'eatit-2dee5',
    storageBucket: 'eatit-2dee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcZI4hdRRVHZFWmTDl012Zj5gTwgJkqY',
    appId: '1:75820450814:ios:238699d252b70af80d36af',
    messagingSenderId: '75820450814',
    projectId: 'eatit-2dee5',
    storageBucket: 'eatit-2dee5.appspot.com',
    androidClientId: '75820450814-ohgfdt7jon8qhpi55oe9vtme9dcls2tl.apps.googleusercontent.com',
    iosClientId: '75820450814-607hsrb3n5coa06j8k81una616tlisqc.apps.googleusercontent.com',
    iosBundleId: 'com.rython.eatit',
  );
}
